# Generated by Django 5.1.4 on 2025-01-31 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0004_message_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('featured_image', models.ImageField(upload_to='images/gallery_main', verbose_name='Featured Image')),
                ('by_who', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='By Who')),
            ],
            options={
                'verbose_name': 'Gallery Room',
                'verbose_name_plural': 'Gallery Rooms',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/gallery', verbose_name='Image')),
                ('caption', models.CharField(max_length=200, verbose_name='Caption')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_module.galleryroom', verbose_name='Gallery Room')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
