# Generated by Django 5.1.4 on 2025-01-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0005_galleryroom_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryroom',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active / Inactive'),
        ),
    ]
