# Generated by Django 5.1.4 on 2025-01-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0006_galleryroom_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryroom',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
