# Generated by Django 5.1.4 on 2025-02-10 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0018_group'),
        ('chat_module', '0008_gallery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account_module.group', verbose_name='Group'),
        ),
    ]
