services:
  web:
    build: .
    container_name: django_app
    restart: unless-stopped
    environment:
      DJANGO_SETTINGS_MODULE: EasyChatProject.settings
    volumes:
      - "media_volume:/usr/src/app/media"
      - "static_volume:/usr/src/app/staticfiles"
    depends_on:
      - db
      - redis
      
  nginx:
    image: nginx:1.23.1-alpine
    restart: unless-stopped
    volumes:
      - "./.ci/nginx/conf.d:/etc/nginx/conf.d"
      - "media_volume:/usr/src/app/media"
      - "static_volume:/usr/src/app/staticfiles"
    ports:
      - "${NGINX_PORT}:15520"
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: ezchatz-postgresezchat-ptmmdz
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped

volumes:
  media_volume:
  static_volume:
  postgres_data:
