# Generated by Django 5.1.4 on 2025-01-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Response'),
        ),
    ]
