# Generated by Django 5.1.4 on 2025-01-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_user_display_name_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='کد ساخته شده'),
        ),
        migrations.DeleteModel(
            name='InvitationCode',
        ),
    ]
