# Generated by Django 5.1.4 on 2025-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_remove_user_code_invitationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Generated Code'),
        ),
    ]
