# Generated by Django 5.1.4 on 2025-01-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_country_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='name',
        ),
    ]
