# Generated by Django 5.1.4 on 2025-02-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_rename_country_logo_country_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='MEDIA_ROOT/images/avatars/face.png', upload_to='images/avatars', verbose_name='Avatar'),
        ),
    ]
