# Generated by Django 5.1.4 on 2025-02-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/avtar/face.png', upload_to='images/avatars', verbose_name='Avatar'),
        ),
    ]
