# Generated by Django 5.1.4 on 2025-02-04 11:46

import utils.get_default_avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=utils.get_default_avatar.get_default_avatar, upload_to='images/avatars', verbose_name='Avatar'),
        ),
    ]
