# Generated by Django 5.1.4 on 2025-02-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0015_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars', verbose_name='Avatar'),
        ),
    ]
