# Generated by Django 5.1.4 on 2025-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0019_group_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About Group'),
        ),
    ]
